<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>index.phtml</title>
</head>
<body>
<h4><?php echo __FILE__;?></h4>
<h5><?php echo $this->templateData['controller'];?></h5>
<?php
    foreach ($this->templateData['colors'] as $color){
        echo '<h4 style="color: '.$color.'" >'.$color.'</h4>';
    }
?>

</body>
</html>