<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>index.phtml</title>
</head>
<body>
<h4>
    <?php
//    echo __FILE__;
    echo 'There are '.count($this->templateData['users']).' Users';

    ?>
</h4>
<!--<h5>--><?php //echo $this->templateData['controller'];?><!--</h5>-->
<?php
    foreach ($this->templateData['users'] as $user){
        echo '<div style="color: darkcyan; width=100%; padding: 20px; border: 2px dashed lightsteelblue; margin-bottom: 10px">'
            .$user->getFirstName().' '
            .$user->getLastName().'<br/>'
            .'<small>'.$user->getEmail().'</small><br/>'.
            '</div>'
        ;
    }
?>k

</body>
</html>